#ifndef BUBBLE_BASE_
#define BUBBLE_BASE_

#define	RET_OK							 0
#define RET_ERROR_DEVICE_IS_NULL		-1
#define RET_ERROR_DEVICE_ALREADY_EXIST	-2
#define RET_ERROR_DEVICE_NOT_FOUND		-3
#define RET_ERROR_DEVICE_UNSINCED		-4
#define RET_ERROR_IO_ALREADY_EXIST      -5
#define RET_ERROR_IO_NOT_FOUND			-6



#endif

